### ISSUE TITLE
version 1.2.0 crash on boot

### ISSUE THREAD

**Issue by RobertoD91** [dji-sdk/DJI-Cloud-API-Demo#5]
After updating to 1.2.0 the backend crash
tried a clean installation

```
cloud_api_sample_120-cloud_api_sample-1  |   .   ____          _            __ _ _
cloud_api_sample_120-cloud_api_sample-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
cloud_api_sample_120-cloud_api_sample-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
cloud_api_sample_120-cloud_api_sample-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
cloud_api_sample_120-cloud_api_sample-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
cloud_api_sample_120-cloud_api_sample-1  |  =========|_|==============|___/=/_/_/_/
cloud_api_sample_120-cloud_api_sample-1  |  :: Spring Boot ::               (v2.4.11)
cloud_api_sample_120-cloud_api_sample-1  | 
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:11.936  INFO 7 --- [           main] c.dji.sample.CloudApiSampleApplication   : Starting CloudApiSampleApplication v1.1.0 using Java 11.0.14.1 on cloud_api_sample with PID 7 (/app/target/cloud-api-sample-1.1.0.jar started by root in /app)
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:11.939 DEBUG 7 --- [           main] c.dji.sample.CloudApiSampleApplication   : Running with Spring Boot v2.4.11, Spring v5.3.10
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:11.940  INFO 7 --- [           main] c.dji.sample.CloudApiSampleApplication   : No active profile set, falling back to default profiles: default
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:12.880  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:12.881  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:12.904  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8 ms. Found 0 Redis repository interfaces.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:13.149  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:13.150  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:13.192  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 40 ms. Found 0 Redis repository interfaces.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:13.484  INFO 7 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:13.489  INFO 7 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:13.495  INFO 7 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.010  INFO 7 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.020  INFO 7 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.022  INFO 7 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.312  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6789 (http)
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.330  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.331  INFO 7 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.53]
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.380  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:14.381  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2386 ms
cloud_api_sample_120-cloud_api_sample-1  | WARNING: An illegal reflective access operation has occurred
cloud_api_sample_120-cloud_api_sample-1  | WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (jar:file:/app/target/cloud-api-sample-1.1.0.jar!/BOOT-INF/lib/spring-core-5.3.10.jar!/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
cloud_api_sample_120-cloud_api_sample-1  | WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
cloud_api_sample_120-cloud_api_sample-1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
cloud_api_sample_120-cloud_api_sample-1  | WARNING: All illegal access operations will be denied in a future release
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:15.213  INFO 7 --- [           main] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:15.560  INFO 7 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
cloud_api_sample_120-cloud_api_sample-1  |  _ _   |_  _ _|_. ___ _ |    _ 
cloud_api_sample_120-cloud_api_sample-1  | | | |\/|_)(_| | |_\  |_)||_|_\ 
cloud_api_sample_120-cloud_api_sample-1  |      /               |         
cloud_api_sample_120-cloud_api_sample-1  |                         3.4.2 
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:18.396  WARN 7 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Invalid mapping on handler class [com.dji.sample.control.controller.DockController]: public com.dji.sample.common.model.ResponseResult com.dji.sample.control.controller.DockController.createControlJob(java.lang.String,java.lang.String)
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:18.402  INFO 7 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:18.409  INFO 7 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:18.440  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:18.473  INFO 7 --- [           main] ConditionEvaluationReportLoggingListener : 
cloud_api_sample_120-cloud_api_sample-1  | 
cloud_api_sample_120-cloud_api_sample-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
cloud_api_sample_120-cloud_api_sample-1  | 2022-09-25 23:28:18.492 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
cloud_api_sample_120-cloud_api_sample-1  | 
cloud_api_sample_120-cloud_api_sample-1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Invalid mapping on handler class [com.dji.sample.control.controller.DockController]: public com.dji.sample.common.model.ResponseResult com.dji.sample.control.controller.DockController.createControlJob(java.lang.String,java.lang.String)
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.11.jar!/:2.4.11]
cloud_api_sample_120-cloud_api_sample-1  | 	at com.dji.sample.CloudApiSampleApplication.main(CloudApiSampleApplication.java:15) ~[classes!/:1.1.0]
cloud_api_sample_120-cloud_api_sample-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
cloud_api_sample_120-cloud_api_sample-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
cloud_api_sample_120-cloud_api_sample-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
cloud_api_sample_120-cloud_api_sample-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[cloud-api-sample-1.1.0.jar:1.1.0]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[cloud-api-sample-1.1.0.jar:1.1.0]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[cloud-api-sample-1.1.0.jar:1.1.0]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[cloud-api-sample-1.1.0.jar:1.1.0]
cloud_api_sample_120-cloud_api_sample-1  | Caused by: java.lang.IllegalStateException: Invalid mapping on handler class [com.dji.sample.control.controller.DockController]: public com.dji.sample.common.model.ResponseResult com.dji.sample.control.controller.DockController.createControlJob(java.lang.String,java.lang.String)
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lambda$detectHandlerMethods$1(AbstractHandlerMethodMapping.java:288) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.core.MethodIntrospector.lambda$selectMethods$0(MethodIntrospector.java:74) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:364) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.core.MethodIntrospector.selectMethods(MethodIntrospector.java:72) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:281) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.processCandidateBean(AbstractHandlerMethodMapping.java:266) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:225) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:213) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:206) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	... 25 common frames omitted
cloud_api_sample_120-cloud_api_sample-1  | Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'url.control.prefix' in value "${url.control.prefix}${url.control.version}/devices"
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.beans.factory.config.EmbeddedValueResolver.resolveStringValue(EmbeddedValueResolver.java:54) ~[spring-beans-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.resolveEmbeddedValuesInPatterns(RequestMappingHandlerMapping.java:381) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.createRequestMappingInfo(RequestMappingHandlerMapping.java:357) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.createRequestMappingInfo(RequestMappingHandlerMapping.java:312) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.getMappingForMethod(RequestMappingHandlerMapping.java:274) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.getMappingForMethod(RequestMappingHandlerMapping.java:76) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lambda$detectHandlerMethods$1(AbstractHandlerMethodMapping.java:284) ~[spring-webmvc-5.3.10.jar!/:5.3.10]
cloud_api_sample_120-cloud_api_sample-1  | 	... 35 common frames omitted
cloud_api_sample_120-cloud_api_sample-1  | 
cloud_api_sample_120-cloud_api_sample-1 exited with code 1
```

**Comment by emilianocds** [comment]
Having same issue here

**Comment by i0c1e** [comment]
[a2d31fc](https://github.com/dji-sdk/DJI-Cloud-API-Demo/commit/a2d31fcd9d5fb0ffc8055bccc54a5357b9f89067)

has fixed

**Comment by emilianocds** [comment]
I updated to last commit and deleted the database and ran mysql: source "path to cloud_sample.sql file" but still having the issue.

**Comment by DJIsean** [comment]
> I updated to last commit and deleted the database and ran mysql: source "path to cloud_sample.sql file" but still having the issue.

modify application.yml. ![image](https://user-images.githubusercontent.com/102007705/197131881-06c3aa6e-c06f-4ad2-b1c6-edb9d1d56836.png)
