### ISSUE TITLE
航线上传后台解析错误com.dji.sdk.cloudapi.device.DeviceEnum has unknown data: [1-65534-0]

### ISSUE THREAD

**Issue by liuzh-hub** [dji-sdk/DJI-Cloud-API-Demo#65]
航线文件已上传到文件存储服务器。但是后台错误。
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.dji.sdk.cloudapi.device.DeviceEnum`, problem: com.dji.sdk.cloudapi.device.DeviceEnum has unknown data: [1-65534-0]
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 141] (through reference chain: com.dji.sdk.cloudapi.wayline.WaylineUploadCallbackRequest["metadata"]->com.dji.sdk.cloudapi.wayline.WaylineUploadCallbackMetadata["payload_model_keys"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2047)
        at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1400)
        at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:182)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3682)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:380)
        ... 54 more
Caused by: com.dji.sdk.exception.CloudSDKException: com.dji.sdk.cloudapi.device.DeviceEnum has unknown data: [1-65534-0]
        at com.dji.sdk.cloudapi.device.DeviceEnum.lambda$find$3(DeviceEnum.java:128)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at com.dji.sdk.cloudapi.device.DeviceEnum.find(DeviceEnum.java:128)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:117)
        at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:171)
        ... 67 more

**Comment by USER-HFC** [comment]
65534是你的负载设备id，这个负载设备不是官方的负载，可以通过修改com.dji.sdk.cloudapi.device.DeviceEnum 来支持你的设备
